job_interview_words = [
    'sad',
    'upset',
    'chocolate',
    'engaging',
    'smashed',
    'Thomas',
    'Thomas',
    'teenager',
    'fishing',
    'pink',
    'subjective',
    'jugular vein',
    'glands',
    'crusts',
    'feral',
    'barn',
    'Cleveland',
    'juggling',
    'Will Smith',
    'brown',
    'suit',
    'gluteus maximus',
    'daughter',
    '105',
    '5000',
    'Will Smith',
    'IKEA',
    'kick',
    'Will Smith',
    'Will Smith',
    'cooked',
    'sniffed',
    'heavy metal',
    'striked',
    'wrapped',
    'elated',
    'angry',
    'hammering',
    'Will Smith']
