print("Creating watch at 5.22 seconds")
watch = StopWatch(5.22)
print(watch)
print("Starting watch and waiting 1 second")
watch.start(); sleep(1); print(watch)
print("Waiting one more second")
sleep(1); print(watch)
print("Stopping and waiting 1 second, watch is the same")
watch.stop(); sleep(1); print(watch)
print("Starting watch again and waiting 1 second")
watch.start(); sleep(1); print(watch)
print("Resetting watch")
watch.reset(); print(watch)
print("Starting and waiting 1 second")
watch.start(); sleep(1); print(watch)
print("Pretty print a watch:", StopWatch(12313.327))
print("equals and <:")
print(StopWatch(5.22) == StopWatch(5.22))
print(StopWatch() < StopWatch(2.0))
print("Stopping a stopped watch raises an exception:")
StopWatch().stop()
print("Starting a started watch raises an exception:")
watch = StopWatch()
watch.start(); watch.start()

